[project]
name = "prompt-pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.24.0",
    "groq>=1.7.0",
    "openai>=3.17.0",
    "psycopg[binary]>=3.3.6",
    "sqlalchemy>=2.0.54",
    "tavily-python>=0.8.4",
]
